'\" t
.\"     Title: taboot-tasks
.\"    Author: [see the "AUTHOR" section]
.\" Generator: DocBook XSL Stylesheets v1.76.1 <http://docbook.sf.net/>
.\"      Date: 06/23/2011
.\"    Manual: Taboot
.\"    Source: Taboot 0.2.x
.\"  Language: English
.\"
.TH "TABOOT\-TASKS" "5" "06/23/2011" "Taboot 0\&.2\&.x" "Taboot"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
taboot-tasks \- quick reference for the built in tasks
.SH "DESCRIPTION"
.sp
Taboot is a tool for written for scripting and automating the task of performing software releases in a large\-scale infrastructure\&. Release scripts are written using YAML syntax\&.
.sp
Taboot tasks are pre\-written actions to perform on a given host\&. For example, scheduling downtime in Nagios, or updating all the RPMs on a system\&. The tasks documented here can be used in \fIpreflight\fR and \fItasks\fR blocks\&. The syntax of each possible tasks varies\&. Taboot comes with many built\-in tasks\&.
.sp
This quick\-reference is example based and only uses abbreviated forms where possible\&.
.SH "COMMAND"
.sp
The \fBCommand\fR task lets you run arbitrary commands on the remote host\&.
.sp
.if n \{\
.RS 4
.\}
.nf
\-\-\-
\- hosts: [www0*\&.company\&.com]
  tasks:
    # Install httpd on all matching hosts
    \- command\&.Run: {command: yum \-y install httpd}
.fi
.if n \{\
.RE
.\}
.SH "SERVICE"
.sp
The \fBService\fR task provides an interface to the system \fIservice\fR command\&.
.sp
.if n \{\
.RS 4
.\}
.nf
\-\-\-
\- hosts: [www0*\&.company\&.com]
  tasks:
    # Start httpd on all matching hosts
    \- service\&.Start: {service: httpd}
    # Stop httpd on all matching hosts
    \- service\&.Stop: {service: httpd}
    # Restart httpd on all matching hosts
    \- service\&.Restart: {service: httpd}
.fi
.if n \{\
.RE
.\}
.SH "PUPPET"
.sp
The \fBPuppet\fR task provides a uniform way to interact with the puppet service\&. This includes enabling/disabling the daemon and manually forcing a catalog run\&.
.sp
.if n \{\
.RS 4
.\}
.nf
\-\-\-
\- hosts: [www0*\&.company\&.com]
  tasks:
    # Enable puppet
    \- puppet\&.Enable
    # Disable puppet
    \- puppet\&.Disable
    # Delete that stubborn lockfile
    \- puppet\&.DeleteLockfile
    # Test run
    \- puppet\&.Run
    # Do a paranoid test run (quit Taboot on possible errors)
    \- puppet\&.SafeRun
.fi
.if n \{\
.RE
.\}
.SH "NAGIOS"
.sp
The \fBNagios\fR task lets you handle notifications and set downtime from your Taboot scripts\&.
.sp
.if n \{\
.RS 4
.\}
.nf
\-\-\-
\- hosts: [www0*\&.company\&.com]
  tasks:
    # Disable alerts for all matching hosts
    \- nagios\&.DisableAlerts:
        nagios_url: nagios\&.example\&.com
    # Enable alerts for all matching hosts
    \- nagios\&.EnableAlerts:
        nagios_url: nagios\&.example\&.com
    # Schedule a 60 minute downtime for httpd, git and XMLRPC on
    # all matching hosts
    \- nagios\&.ScheduleDowntime:
        nagios_url: nagios\&.example\&.com
        service: [httpd, git, XMLRPC]
        minutes: 60
.fi
.if n \{\
.RE
.\}
.SH "SLEEP"
.sp
The \fBSleep\fR task is used to halt further task processing for a specified period of time\&.
.sp
.if n \{\
.RS 4
.\}
.nf
\-\-\-
\- hosts: [www0*\&.company\&.com]
  tasks:
    # Pauses execution for 5 minutes
    \- sleep\&.Seconds: {seconds: 300}
    # Also pauses execution for 5 minutes
    \- sleep\&.Minutes: {minutes: 5}
.fi
.if n \{\
.RE
.\}
.SH "YUM"
.sp
The \fBYum\fR task lets you install, remove, and update RPMs right in your Taboot scripts\&.
.sp
.if n \{\
.RS 4
.\}
.nf
\-\-\-
\- hosts: [www0*\&.company\&.com]
  tasks:
    # Install three packages
    \- yum\&.Install: {packages: [httpd, php5, screen]}
    # Remove the same three packages
    \- yum\&.Remove: {packages: [httpd, php5, screen]}
    # Update the same three packages
    \- yum\&.Update: {packages: [httpd, php5, screen]}
.fi
.if n \{\
.RE
.\}
.SH "RPM"
.sp
The \fBRPM\fR task provides two utility actions that, when used together, report any RPMs that changed between the PreManifest and PostManifest\&.
.sp
.if n \{\
.RS 4
.\}
.nf
\-\-\-
\- hosts: [www0*\&.company\&.com]
  tasks:
    # Take a PreManifest of all installed packages
    \- rpm\&.PreManifest
    # Use yum to update all the system RPMs\&.
    \- yum\&.Update
    # Take a PostManifest and diff it against the PreManifest
    # The diff is printed after PostManifest finishes running\&.
    \- rpm\&.PostManifest
.fi
.if n \{\
.RE
.\}
.SH "AJP"
.sp
The \fBAJP\fR task provides a uniform way to put nodes into and out of rotation in a mod_jk AJP balancer\&. This module is a great replacement for manually adding and removing nodes in a jkmanage management panel\&.
.sp
.if n \{\
.RS 4
.\}
.nf
\-\-\-
\- hosts: [tomcat*\&.int\&.company\&.com]
  tasks:
    # Take the matching node out of rotation
    \- mod_jk\&.OutOfRotation:
        proxies:
            \- proxyjava01\&.web\&.prod\&.int\&.example\&.com
            \- proxyjava02\&.web\&.prod\&.int\&.example\&.com
    # Do stuff\&.\&.\&.\&.
    # do more stuff\&.\&.\&.
    # Put the node back into the pool
    \- mod_jk\&.InRotation:
        proxies:
            \- proxyjava01\&.web\&.prod\&.int\&.example\&.com
            \- proxyjava02\&.web\&.prod\&.int\&.example\&.com
.fi
.if n \{\
.RE
.\}
.SH "AUTHOR"
.sp
Taboot was originally written by John Eckersberg\&. Tim Bielawa is the current maintainer\&. See the AUTHORS file for a complete list of contributors\&.
.SH "COPYRIGHT"
.sp
Copyright \(co 2009\-2011, Red Hat, Inc
.sp
Taboot is released under the terms of the GPLv3+ license\&.
.SH "SEE ALSO"
.sp
\fBtaboot\fR(1), \fBfunc\fR(1)
.sp
Taboot home page: https://fedorahosted\&.org/Taboot/
.sp
HTML Docs: http://people\&.redhat\&.com/~tbielawa/taboot/docs/taboot\-latest/tasks\&.html
