taboot(1)
=========
:doctype:manpage
:man source:   Taboot
:man version:  0.4.x
:man manual:   System administration commands

NAME
----
taboot - run a taboot release script



SYNOPSIS
--------
taboot [-h] [-V] [-v] [-n | -p] [-s | -o] [-L [LOGFILE]]
              [-C CONCURRENCY] [-E] [FILE [FILE ...]]




DESCRIPTION
-----------

Taboot is a tool written for scripting and automating the task of
performing software releases in a large-scale infrastructure. Release
scripts are written using YAML syntax.




OPTIONS
-------

*FILE*::

Release file in YAML format. Instructions are read from stdin if
'FILE' is '-' or not given. Multiple __FILE__s can be given.



*-h*, *--help*::

Show this help message and exit.



*-V*, *--version*::

Show program's version number and exit.



*-v*, *--verbose*::

Increase verbosity. Give up to twice.



*-n*, *--checkonly*::

Don't execute the release, just check script syntax.



*-p*, *--printonly*::

Don't execute the release, just check script syntax and print the YAML
to be run to stdout.



*-s*, *--skippreflight*::

Skip preflight sections if they exist.



*-o*, *--onlypreflight*::

Only run preflight sections.



*-L [LOGFILE]*, *--logfile [LOGFILE]*::

Adds a LogOutput type to the script(s) being run. If __LOGFILE__ is
not specified then taboot-YYYY-MM-DD-HHMMSS.log will be used.



*-C CONCURRENCY*, *--concurrency CONCURRENCY*::

Set the concurrency for the input script(s). Give as an integer, or
'all' for max concurrency.



*-E*, *--edit*::

Edit the input script(s) before running them using $EDITOR. This falls
back to emacs and then vi. The **tabootv** command will choose vi
automatically.




AUTHOR
------

Taboot was originally written by John Eckersberg. Tim Bielawa is the
current maintainer. See the AUTHORS file for a complete list of
contributors.


COPYRIGHT
---------

Copyright © 2009-2011, Red Hat, Inc

Taboot is released under the terms of the GPLv3+ license.



SEE ALSO
--------
*taboot-tasks*(5), *func*(1)


Taboot home page: <https://fedorahosted.org/Taboot/>

HTML Docs: <http://people.redhat.com/~tbielawa/taboot/docs/taboot-latest/>
